package com.example.calculatorpro.theme

import androidx.compose.ui.graphics.Color

// Dark Palette
val DarkBackground = Color(0xFF131313)
val DarkOnBackground = Color(0xFFE5E2E1)
val DarkSurface = Color(0xFF131313)
val DarkOnSurface = Color(0xFFE5E2E1)
val DarkSurfaceVariant = Color(0xFF353535)
val DarkPrimary = Color(0xFFFFB1C0)
val DarkOnPrimary = Color(0xFF660029)
val DarkPrimaryContainer = Color(0xFFFF4C83)
val DarkOnPrimaryContainer = Color(0xFF5A0023)
val DarkSecondary = Color(0xFFC8C6C5)
val DarkOnSecondary = Color(0xFF313030)
val DarkSecondaryContainer = Color(0xFF4A4949)
val DarkOnSecondaryContainer = Color(0xFFBAB8B7)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkOutline = Color(0xFFAB888E)

// Light Palette (Inferred High-Contrast)
val LightBackground = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF131313)
val LightSurface = Color(0xFFF5F5F5)
val LightOnSurface = Color(0xFF131313)
val LightSurfaceVariant = Color(0xFFE0E0E0)
val LightPrimary = Color(0xFFBC0051)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFB1C0)
val LightOnPrimaryContainer = Color(0xFF3F0017)
val LightSecondary = Color(0xFF4A4949)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE5E2E1)
val LightOnSecondaryContainer = Color(0xFF1C1B1B)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightOutline = Color(0xFF5B3F44)
